; cabeza: por fotograma, n y n veces (fila, columna, tile).
DragonCabeza0:
    db 11
    db 0, 1, 0
    db 0, 2, 1
    db 0, 3, 2
    db 1, 0, 3
    db 1, 1, 4
    db 1, 2, 5
    db 1, 3, 6
    db 2, 0, 7
    db 2, 1, 8
    db 2, 2, 9
    db 2, 3, 10
DragonCabeza1:
    db 12
    db 0, 0, 11
    db 0, 1, 12
    db 0, 2, 13
    db 0, 3, 14
    db 1, 0, 15
    db 1, 1, 16
    db 1, 2, 17
    db 1, 3, 18
    db 2, 0, 19
    db 2, 1, 20
    db 2, 2, 21
    db 2, 3, 22
DragonCabeza2:
    db 12
    db 0, 0, 23
    db 0, 1, 24
    db 0, 2, 25
    db 0, 3, 26
    db 1, 0, 27
    db 1, 1, 28
    db 1, 2, 29
    db 1, 3, 30
    db 2, 0, 31
    db 2, 1, 32
    db 2, 2, 33
    db 2, 3, 34
DragonCabeza3:
    db 12
    db 0, 0, 35
    db 0, 1, 36
    db 0, 2, 37
    db 0, 3, 38
    db 1, 0, 39
    db 1, 1, 40
    db 1, 2, 41
    db 1, 3, 42
    db 2, 0, 43
    db 2, 1, 44
    db 2, 2, 45
    db 2, 3, 46
DragonCabeza4:
    db 11
    db 0, 1, 47
    db 0, 2, 48
    db 0, 3, 49
    db 1, 0, 50
    db 1, 1, 51
    db 1, 2, 52
    db 1, 3, 53
    db 2, 0, 54
    db 2, 1, 55
    db 2, 2, 56
    db 2, 3, 57
DragonCabeza5:
    db 11
    db 0, 1, 58
    db 0, 2, 59
    db 0, 3, 60
    db 1, 0, 61
    db 1, 1, 62
    db 1, 2, 63
    db 1, 3, 64
    db 2, 0, 65
    db 2, 1, 66
    db 2, 2, 67
    db 2, 3, 68
