; rugido: por fotograma, n y n veces (fila, columna, tile).
DragonRugido0:
    db 24
    db 0, 0, 0
    db 0, 1, 1
    db 0, 2, 2
    db 0, 3, 3
    db 1, 0, 4
    db 1, 1, 5
    db 1, 2, 6
    db 1, 3, 7
    db 1, 4, 8
    db 2, 0, 9
    db 2, 1, 10
    db 2, 2, 11
    db 2, 3, 12
    db 2, 4, 13
    db 3, 0, 14
    db 3, 1, 15
    db 3, 2, 16
    db 3, 3, 17
    db 3, 4, 18
    db 4, 0, 19
    db 4, 1, 20
    db 4, 2, 21
    db 4, 3, 22
    db 4, 4, 23
DragonRugido1:
    db 28
    db 0, 0, 24
    db 0, 1, 25
    db 0, 2, 26
    db 0, 3, 27
    db 0, 4, 28
    db 1, 0, 29
    db 1, 1, 30
    db 1, 2, 31
    db 1, 3, 32
    db 1, 4, 33
    db 1, 5, 34
    db 2, 0, 35
    db 2, 1, 36
    db 2, 2, 37
    db 2, 3, 38
    db 2, 4, 39
    db 2, 5, 40
    db 3, 0, 41
    db 3, 1, 42
    db 3, 2, 43
    db 3, 3, 44
    db 3, 4, 45
    db 3, 5, 46
    db 4, 1, 47
    db 4, 2, 48
    db 4, 3, 49
    db 4, 4, 50
    db 4, 5, 51
