; Generado por generar_arte_v1.py. CGB BGR555, 4 colores por paleta.
; 4 BG + 4 OBJ = 8 paletas totales.

MyrmidonPal_BG_MARMOL::
    dw $0C42, $2D07, $5A92, $639E
MyrmidonPal_BG_COLUMNA::
    dw $0C42, $2509, $4E96, $639E
MyrmidonPal_BG_ESTANTE::
    dw $0C42, $1CA7, $2954, $475D
MyrmidonPal_BG_AGUA::
    dw $0C42, $2904, $524A, $6F78
MyrmidonPal_OBJ_AQUILES::
    dw $0000, $1CA4, $51CA, $5F5C
MyrmidonPal_OBJ_GUARDIA::
    dw $0000, $1486, $1D34, $3F3D
MyrmidonPal_OBJ_HUD::
    dw $0000, $1CC4, $568E, $639E
MyrmidonPal_OBJ_VULNERABLE::
    dw $0000, $1487, $1D77, $3F7E
